/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class librasta_RastaNative */

#ifndef _Included_librasta_RastaNative
#define _Included_librasta_RastaNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     librasta_RastaNative
 * Method:    librasta_init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_librasta_RastaNative_librasta_1init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     librasta_RastaNative
 * Method:    librasta_send
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_librasta_RastaNative_librasta_1send
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     librasta_RastaNative
 * Method:    librasta_disconnectFrom
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_librasta_RastaNative_librasta_1disconnectFrom
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     librasta_RastaNative
 * Method:    librasta_cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_librasta_RastaNative_librasta_1cleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
